### ISSUE TITLE
Smoothing is piling-up time lag between screen and LEDS

### ISSUE THREAD

**Issue by hkalle** [awawa-dev/HyperHDR#145]
## Bug report, debug log and your config file (FULL LOGS ARE MANDATORY)
https://pastebin.com/ny5c5VwW

#### Steps to reproduce
Activate HyperHDR without smoothing --> no time lag
Activate smoothing --> Time lag increases the longer HyperHDR is running

#### What is expected?
No major influnce of smoothing on time lag between screen and LEDs
No increase of time lag with run time of HyperHDR. It seems that HyperHDR is piling up the delay time.
What I addionally recoginzed: Even if I specify an update frequency of 20 in the web interface the log reports "interval: 40ms (25Hz)"

#### What is actually happening?
Time lag is constantly increasing with run-time of HyperHDR

#### System
Behaviour can be reproduced under Windows with DirectX grabber and RasberryPi 3b+ with external grabber. Logs have been created on windows system

HyperHDR Server: 
- Build:           (HEAD detached at dec81c0) (Awawa-2a2ed8d/dec81c0-1631541363)
- Build time:      Sep 15 2021 15:59:04
- Git Remote:      https://github.com/awawa-dev/HyperHDR
- Version:         17.0.0.0
- UI Lang:         en (BrowserLang: de)
- UI Access:       default
- Avail Capt:      Windows (Microsoft Media Foundation)
- Database:        read/write

HyperHDR Server OS: 
- Distribution:   Windows 10 Version 2009
- Architecture:   x86_64
- Kernel:         winnt (10.0.19043 (WS: 64))
- Qt Version:     5.15.2
- Browser:        Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36 Edg/95.0.1020.44

**Comment by hkalle** [comment]
Forgot to mention, that it worked as expected in verion 16.1.

**Comment by awawa-dev** [comment]
But DX grabber was not present in v16. Can't see a problem frankly. Diagnostic can a problematic for particular setup external network LED instances such as WLED over wifi because a lot depends on the connection stability and even 25Hz could be too much sometimes. You can lower delay to from 150ms to ~50ms in the smoothing settings to have better response time also.

**Comment by hkalle** [comment]
Hello awawa-dev
Thanks for your quick response!

I used the raspberry pi version with 16.1 on my "productive" system. Also understand that set-up with WLED is hard to judge on.

I tried to lower the update frequency to 10 fps and still in the log it is reported as 25Hz. According to the log I am not able to lower it less than 25Hz, whatever I enter. I can increase > 25Hz, but not decrease.

Could you maybe please check if the update frequency I enter into the webgui is correctly applied?

2021-11-12T10:05:16.120Z [SMOOTHING0] Selecting config (0) => type: Alternative, dirMode: false, pause: false, settlingTime: 50ms, interval: 40ms (25Hz), antiFlickTres: 32, antiFlickStep: 1, antiFlickTime: 250

Thanks!

**Comment by awawa-dev** [comment]
although web-gui allows to input as low as 1Hz, then in the smoothing procedure it's verified and 25Hz is set as minimum. I could to set same limit in both units but very doubt it will change anything in your situation and very low refresh rate makes the smoothing looks bad anyway. Lets say 25Hz is lowest usable.

if the wifi connection is lost from time to time even for a very short time it could result in such behavior as your. Other possibility is the router itself. But it's hard to judge if the previous version works better for you: major changes in smoothing was made in v16, in v17 are only cosmetic and they couldn't alone change behavior definitely in such dramatic way. And I'm very confident about it. WLED network protocol on the other hand changed a bit to fix one problem but then it should affect also no-smoothing scenario.

You can assess the maximum WLED throughput but enabling 'continues output'  and settings rather high refresh rate (for example 50Hz) in the smoothing (video source or some effect must be active anyway). Then in WLED's statistics panel you can read the final refresh rate. Refresh rate in HyperHDR should be set lower than maximum achieved refresh rate in WLED, But it is not a scientific method and you can miss drop in the packages delivery (and WLED refresh rate) if they appears only from time to time.

Other border-possibility that could affects smoothing is completely running out of system resources (CPU/RAM) but it's unlikely in your case as that happens for both your OS/devices. But WLED/network is one common thing that connects the problem so I would dig deeper around it.

**Comment by hkalle** [comment]
Your are correct. My wifi seems to be the bottleneck though I did not thought newwork through-put for wled would be that high.

Also I seem to understand, why it is not a problem without smoothing being activated. If smoothing is off I assume the LED update frequency is equal the capture frequency and in my case it is 20fps, what my wifi can perfectly manage. By activating smooting with 20 Hz the LED update frequency is going up to 25 Hz as minimum and I run into delay.

For me 20 fps also for smoothing is absolutely enough. I compared it to Hyperion-NG, where lower rates are possible. Of course I would like to benefit from HyperHDR (3dLUT, HDR and anti-flickering). Could you please take into account to let lower smoothing rates than 25Hz to be set. Thanks a lot!

**Comment by awawa-dev** [comment]
What was your best result when testing max throughput with WLED and continues output in HyperHDR? I'm asking because there is a very small chance that for some configuration/setups WLED may be limiting your performance. Especially since you have over 300leds (what model?). 
It's not problem for me to unify web page settings with internal smoothing module and set for example 15Hz as minimum for both. But I would suggest first to set grabber to 25Hz and disable smoothing just to be sure it will help anyway.

**Comment by hkalle** [comment]
I cannot go over 20fps, but the network througput is minimal (~18KB/s). I am using APA102 LEDs and of course it could be WLED is limiting the performance with 302 LEDs. Need to do some research.

**Comment by awawa-dev** [comment]
18Kb/s indicates that hyperhdr is sending just 20fps (~3B*302  *  20). You must enable smoothing with continues output and have video/capturing source (not effects because some have their own smoothing settings independent from the user...don't remember which exactly, but should be visible in the log when the effect start to play)

**Comment by hkalle** [comment]
If I activate smoothing with 20fps & continues output, network goes up to 23KB/s. But wled does not work anymore, since 25 fps are sent in reality, I also recognized that in that case wled becomes unresponsive with an error (connection to light failed).
Unfortunately 20 fps seems to be the max for my set-up.

**Comment by awawa-dev** [comment]
Which WLED version and ESP32 or ESp8266? Do you use default WLED pinouts for SPI? Seems a bit like WLED runs out of resources but it shouldn't because it's just a SPI for APA102...unless it works under software emulation.

**Comment by hkalle** [comment]
It is an ESP8266. Data GPIO = 2 and clock GPIO = 4. For clock default would be GPIO 0. Reason is, that I use a board where GPIO 4 is passed through for the clock.

**Comment by awawa-dev** [comment]
If it's not a hardware SPI outputs (or not correctly detected by the library if it's non-reference design) for that boards then WLED is probably is using bit bang instead of hardware interface. ESP8266 contrary to ESP32 is not capable of pinout remapping
[https://github.com/Makuna/NeoPixelBus/wiki/NeoPixelBus-object#dotstarspimethod](https://github.com/Makuna/NeoPixelBus/wiki/NeoPixelBus-object#dotstarspimethod)
So the root of the problem lies probable in the ESP hardware, its configuration or WLED. Anyway since Smoothing lower limit was different in the GUI than in the Smoothing module I changed that with the newest commit (lower limit is set to 20Hz globally).

**Comment by hkalle** [comment]
Hi awawa

Thanks again for the excellent support and for bringing HyperHDR to the community!

Your hints made me dig deeper into the ESP8266, WLED and APA102 and your conclusion was correct: For hardware SPI on the ESP8266 you need to connect GPIO14: SCLK for the CLK and GPIO13: MOSI for data. I can easily go up to 50 fps, even I understood that WLED is limiting to 42 Hz maximum.

WLED is suggestion GPIO2 as default data pin and actually I could not find any consistent documentation on how to use pins for APA102 leds. 

I will also post it in the WLED forum. It may help others.
