### ISSUE TITLE
HDR Color issue : green tint

### ISSUE THREAD

**Issue by corecompl3x** [awawa-dev/HyperHDR#20]
Hello,
first of all I want to thank you for your hard work. Everything works flawlessly with HyperHDR and your WLED fork. 
I only have one problem. That is I do have a green tint which results in unsatisfying LED colors especially in darker scenes.
I am not sure if it is a LUT issue when HDR tone mapping is enabled or my cheapo grabber (MS 2109 brown version with USB 3.0 colored connector).  No issues watching SDR content with tonemapping disabled.
Here is a picture of what my grabber live preview looks like when playing an HDR movie with tonemapping enabled via netflix on a PS4 pro.
https://gyazo.com/3c7e03bb021ea2e6fd50d8ab79482b82
My usb capture settings:
https://gyazo.com/c8a49c0b7890f44e811119e7cee51351
I hope someone might know the cause of this behaviour and can propose a fix for this.

Greetings and a happy new year

**Comment by awawa-dev** [comment]
Hi
Try to play with Hue in the grabber settings or classic with the instance calibration to reduce green by gamma. HDR correction in that form is best result from the experiments from Fast-HDR project but I would welcome new & improved one ;) if someone has some idea. HDR table generator is available in the HyperHDR as java-script and can be easily improved for ex. for channel correction/gamma editor (instead doing that in the instance calibration). Threshold minimum level could be also introduced at zero CPU cost. But 99% of users stick to default LUT table without even discovering the generator so that idea has low priority for me.
Best regards and Happy New Year :)

**Comment by corecompl3x** [comment]
Hue -4 in hue control in capture settings, increasing green gamma to 1.6 from 1.5 and reducing greenchannel from 255 to 245 fixed it.
Thanks alot looks perfect now.
