### ISSUE TITLE
EZCAP 269 not working as expected

### ISSUE THREAD

**Issue by appleimperio** [awawa-dev/HyperHDR#27]
Hi, Im using a RPI 4 with MS2109 capturing MJPEG at 1280x720 30fps but recently I bought a Ezcap 269 hoping to get better results but I can't see the difference, in fact I think the MS2109 looks much better.The Ezcap is capturing YUV ar 1920x1080 30fps. I was looking for the specific lut for the Ezcap 269 but I only find the 320 one. can someone point me to the link for this lut file and post the settings in hyperhdr for this device, maybe I'm missing something. Thank You!

**Comment by awawa-dev** [comment]
Hi
I replied you on the blog.

**Comment by Bascht74** [comment]
@awawa-dev Can you provide the link to the blog entry or answer here as well. 
I am thinking about buying an EZCAP269 as well. I don't find that entry where to get the LUT for the EZCAP269.

**Comment by awawa-dev** [comment]
Ezcap 269 uses standard LUT table for HDR tone mapping. The main advantage of that device is quite capable internal splitter, otherwise simply MS2109 offers much better quality in MJPEG stream, 269's stream of 269 isn't great either (visible artifacts due to some internal processing).
Ezcap 321 needs a special LUT table (the only dedicated LUT table available in the downloads alongside the release) because that device does some kind of initial tone mapping and we need to correct it because otherwise: you will have a way too much green almost everywhere, and red in pure blue. And it's impossible to corrected it using hue/saturation controls because it's non linear deviation and that device doesn't support them either way.

**Comment by Bascht74** [comment]
Thx for that info. I will try the ezcap 269 then...
