### ISSUE TITLE
18 beta3: MS2109 black is not black 

### ISSUE THREAD

**Issue by smoki3** [awawa-dev/HyperHDR#309]
https://pastebin.com/R3FMxirt

## Bug report, debug log and your config file (FULL LOGS ARE MANDATORY)
I am using the new beta3 v18. I also using the new lut tables for the MS2109. According to the doc i set the brightness to 1 and saturation contrast to 128. Now the problem is that with a brightness of 1 black is not black anymore.  

#### What is expected?

The leds are going when there is no signal or black 

#### What is actually happening?

Leds slightly lighting

#### System

```
HyperHDR Server: 
- Build:           (HEAD detached at 8d314bc) (Awawa-5b8ed09/8d314bc-1654356765)
- Build time:      Jun  4 2022 15:52:13
- Git Remote:      https://github.com/awawa-dev/HyperHDR
- Version:         18.0.0.0beta3
- UI Lang:         auto (BrowserLang: de-DE)
- UI Access:       expert
- Avail Capt:      Linux (V4L2)
- Database:        read/write
```

**Comment by awawa-dev** [comment]
Hi 
Black on input doesn't mean black on the output (LED/HyperHDR). And grabbers very rarely provide RGB(0,0,0) for the "black" as the user perceive the TV "black" screen. There are various aspects that may affect the result since not other information are provided (even such basic if it's SDR or HDR, if it's black Rullz or other MS2109 clone of the clone) I can only propose you to make a calibration yourself and verify calibration logs. That's not a bug.
