### ISSUE TITLE
memory leak with usb led update

### ISSUE THREAD

**Issue by ManuVice** [awawa-dev/HyperHDR#331]
#### Steps to reproduce
Use an USB Led like Karatelight

#### What is expected?
A normal memory consumption

#### What is actually happening?
Memory + swap fills up after a while. My Raspberry crashes because it is out of memory.
Same problem I've got with Hyperion ng 
see [hyperion ng issue](https://github.com/hyperion-project/hyperion.ng/issues/1425)

I have to you cgroups to limit memory consumption and have to restart hyperhdr every 30min to not crash the hole system.

#### System

[Log](https://pastebin.com/Ruj8LNSK)

HyperHDR Server: 
- Build:           (HEAD detached at 1c31205) (Awawa-e327d52/1c31205-1661084784)
- Build time:      Aug 21 2022 14:03:34
- Git Remote:      https://github.com/awawa-dev/HyperHDR
- Version:         18.0.0.0
- UI Lang:         en (BrowserLang: de-DE)
- UI Access:       expert
- Avail Capt:      Linux (V4L2)
- Database:        read/write

HyperHDR Server OS: 
- Distribution:   Debian GNU/Linux 11 (bullseye)
- Architecture:   arm64
- CPU Type:       Raspberry Pi 3 Model B Rev 1.2
- CPU Revision:   a02082
- CPU Hardware:   BCM2835
- Kernel:         linux (5.15.61-v8+ (WS: 64))
- Qt Version:     5.15.2
- Browser:        Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36

**Comment by awawa-dev** [comment]
Hi
I doubt it's a LED driver problem. Could you disable the black border detection and check again? Also your framerate isn't constant: is HyperHDR the only user app running at the time and what's the reading of cpu usage in ```htop```?

**Comment by ManuVice** [comment]
thanks for your fast reply. I refer this issue to the comment from Lord-Grey hyperion dev, but I'm not tied to it.
> Edit: No need for further testing. Seems I identified some issue in context of the LED update…

I have only HyperHDR and a hdmi-cec script for start/stop HyperHDR running. After your reply I have disabled black border detection and rebooted my device.
Memory grows up and after 30-45min without memory limit my Raspberry will crash. Tested it few hours ago. Same behavior like with hyperion. I dont know which version but it was a hyperion alpha version which worked fine in past.

After a reboot with disabled black border detection
![after reboot](https://user-images.githubusercontent.com/555893/188318314-2df1bb1d-09e7-470b-acdc-482ef4f85d6e.png)

After 10min
![after 10min](https://user-images.githubusercontent.com/555893/188318585-92875bac-768b-4c65-a6d0-34a21ca7610d.png)

After 15min
![15min](https://user-images.githubusercontent.com/555893/188318763-4c487115-43aa-4ab1-8b79-30d3458c03e4.png)

**Comment by awawa-dev** [comment]
And if you change the LED driver from Karate to `Debug>output to the file`, it behaves the same?

**Comment by awawa-dev** [comment]
BTW 160MB after 15 minutes is not a bad result: remember that HyperHDR is using 50MB LUT table loaded to memory. And video frames caching also takes some resources. Please send me your exported HyperHDR config.

**Comment by awawa-dev** [comment]
BTW 160MB after 15 minutes is not a bad result: remember that HyperHDR is using 50MB LUT table. And video frames caching also takes some. Please send me your exported HyperHDR config.

**Comment by ManuVice** [comment]
> HyperHDR is using 50MB LUT table loaded to memory
Ok I didnt know. 

I have disabled cgroups and will try output to file and after a hour back to karatelight

[HyperHDR-18.0.0.0-Backup-2022-09-04.zip](https://github.com/awawa-dev/HyperHDR/files/9485072/HyperHDR-18.0.0.0-Backup-2022-09-04.zip)

**Comment by awawa-dev** [comment]
I tried your configuration. Similar result for 1GB Rpi 3.
![obraz](https://user-images.githubusercontent.com/69086569/188326273-a7e07d7e-eaa2-4786-af79-bd4150573e27.png)
HyperHDR was using Karate driver with esp serial port so I changed only that serial port address. It's one direction communication so it doesn't matter. I have probably the same grabber (MS2109) so didn't need to change its settings.
Logs:
https://pastebin.com/LkY5btLg
No problem at all. As you can see the video frame processing is rock stable (25FPS, 1500 frames per minute, in your it's fluctuating). So probably I suspect something is wrong with the hardware (voltage problem or the USB karate driver causing some low level issues) or the OS (did you tried raspberry pi os instead of Dietpi?).

**Comment by ManuVice** [comment]
After 20min Iam now at with karate and without black bar
![karate](https://user-images.githubusercontent.com/555893/188326919-f5f8d25a-c1fa-4b2e-b754-a844e73a85e9.png)

No didnt tried Raspi OS but will do it right away. 
Power adapter of karatelight is a new one. Because of fluctuating fps I will try change cpu gov from schedutil to performance.
Next step is Raspi OS. Will report shortly and many thanks in advance

**Comment by awawa-dev** [comment]
I thought rather about Rpi power supply (and devices that are supplied by Rpi). In worst case scenario you may experience the same problem as I did sometime ago and that's why HyperSPI was created. Look here https://github.com/awawa-dev/HyperSPI also FPS fluctuations due to poor USB hub management by OS or just Rpi system limitation. But it should not happen for such low grabber resolution unless karate device really messed up the USB bus. And it should be easy to rule this out by disconnecting the karatelight device and then measuring the grabber's FPS in HyperHDR.

Also take a look into ```dmesg``` because maybe something interesting is there. Raspbian should also output under voltage message there (HyperHDR v18 should detected it and warn about it). I think you should first stabilize your USB grabber performance because something is not quite right. Later if it's possible try to lower karate driver speed in HyperHDR.

**Comment by ManuVice** [comment]
With Raspi OS I have the same problem with memory. FPS fluctuations is unstable between 6-14ms.

Many thanks for your help. Iam back at Dietpi and will follow your advice.  I will report😉

**Comment by awawa-dev** [comment]
The processing time is a bit different thing: it can vary slightly depending on the incoming stream (LUT memory access time plays the main part), but I don't know if it should be that long 6-14ms. You should measure this on a still video or on the no signal while the HDMI cable is disconnected from the grabber. The FPS/incoming frames, on the other hand, should be independent of the video stream.

**Comment by ManuVice** [comment]
> Maybe its a problem with Rpi. Without Karatelight connected to Rpi its 10-11ms and seems pretty stable
output is file and cpu usage is around stable 30%. much better than with connected karatelight.

**Comment by ManuVice** [comment]
Hi, I have tried something different. No processes in background + pluged out all devices.

1st I have pluged out all devices. Running only RJ45 + USB grabber [log](https://pastebin.com/rDJJi6xa) 
it seems running fine. memory starts at 98M and goes up to stable ~120M.

after that my 2nd idea was only connect RJ45 + Karatelight and activate effect "rainbow swirl fast" [log](https://pastebin.com/BidbWy1e)
memory was starting at 28M and after 1 hour it was 389M. after stopping the effect memory wasnt freed.
![Screenshot 2022-09-05 220902](https://user-images.githubusercontent.com/555893/188509315-1fe20d6e-0b52-45db-a6a1-138e4cac84bb.png)

is there any dirty hack to free the consumed memory or is it a hardware fault?

**Comment by awawa-dev** [comment]
There is no classic garbage collector in c++/qt. And in HyperHDR almost all objects are released simply when they come out of the scope with one important exception: video frames that must be handled carefully in other way. The hardware failure does not behave that way, but kernel driver CAN cause it. And ff it get stuck and it still receives data from HyperHDR, all the diagnostic programs will report that memory as used by HyperHDR. Since I cannot reproduce the problem even using your exactly configuration, I don't have more clues.

**Comment by ManuVice** [comment]
Thank you very much for your help

I will test police light and an older kernel tommorow.

**Comment by ManuVice** [comment]
its getting weird... Iam closing this...

tested kernel 4.19 same problem.. tested hyperion alpha8 with kernel 4.19 no memory problems. kernel 5.10 with alpha8 no problem.
after that I was going go up with versions to find the one which have the mem problem... I was going straight to 2.0.13..... no problems...

Then tested HyperHDR... problem.. Purged Hyperion and HyperHDR. Just installed hyperhdr fresh DB.. problem... purged it and installed Hyperion 2.0.13 again... works....

Iam sorry but this is getting freaky. It didnt work in past and Ive tried everything, wiped everything, setting up everything from scratch... and now it just works.

Thank you very much for your help. I will look into HyperHDR in future, because it looks much better than Hyperion to me.

**Comment by awawa-dev** [comment]
Thank you for the support. As your problem comes and goes probably it's better in your situation not to change the setup again, since the cause is still unknown. Or make new tests using backup SD card. Hope it will be resolved in the future. . You may also try to compile HyperHDR in debug mode and run it with valgrind to check definitely memory leaks on your setup.

**Comment by ManuVice** [comment]
I have seen another weird error 😂
Did another test. 
Installed Hyperion from its official apt repo... memory leak. Apt removed it... and installed `apt install ./Hyperion-2.0.13-Linux-aarch64.deb`
and no problem no memory problem 😂😂

> You may also try to compile HyperHDR in debug mode and run it with valgrind to check definitely memory leaks on your setup.

I will do and if I find something interessting I will report it to you 👍👍

**Comment by awawa-dev** [comment]
So probably you have a point where you can start: verify if the main app from both repo is the same and in next step compare distributed companion libraries from its lib folder.
