### ISSUE TITLE
Coreelec Plug-in for coreelec 21

### ISSUE THREAD

**Issue by greyvv** [awawa-dev/HyperHDR#585]
#### What problem does this feature solve?
The addon for corelec 20 doesnt work with 21
#### Are you willing to work on this yourself?
no

**Comment by awawa-dev** [comment]
Hi
You can take this commit https://github.com/awawa-dev/CoreELEC/commit/bf72df901e3dd48cc01cbe04ce78c7e7081c3405 (optionally: update HyperHDR version similar way like https://github.com/awawa-dev/CoreELEC/commit/398dc9b79a4ba402a0aecdc304fd95777341908e) apply it to the coreelec 21 and try to build it yourself. Since the package is working for current version corelec version 20, I dont plan further work until version 21 is released.
