### ISSUE TITLE
DDP and WLED segment streaming

### ISSUE THREAD

**Issue by Cheerpipe** [awawa-dev/HyperHDR#616]
## Feature request

Currently, HyperioNG supports DDP as a UDP Protocol and the use of segments on WLED. Could be nice to backport those features to HyperHDR WLED appears to be very popular and used among HyperHDR/HyperionNG users.

#### What problem does this feature solve?

1.- HyperHDR can't stream to specific WLED segments. 
2.- https://github.com/awawa-dev/HyperHDR/issues/573

#### What does the proposed API look like?

n/a

#### How should this be implemented in your opinion?

HyperionNG has implemented DDP and WLED segment handling.

#### Are you willing to work on this yourself?

I can't code C/C++ but can do testing.

#### Related HyperioNG changes

DDP: 

- https://github.com/hyperion-project/hyperion.ng/commit/e9936e131b667292cc3a2dc559c2cc25261dae86

WLED Segments:

- https://github.com/hyperion-project/hyperion.ng/commit/a57bcbc2b8719eb61d45fa8210e6776ccb3729ee
- https://github.com/hyperion-project/hyperion.ng/commit/bf418686e38f674754e0639f158a8ccaf6e40688
- https://github.com/hyperion-project/hyperion.ng/commit/64642a44578fe48dce8144c23180d29c160c7906

**Comment by awawa-dev** [comment]
Hi
I don't think such WLED segments are useful in HyperHDR, because WLED can already implement them internally without the help of an external application (configure multiple multiple led strip treated like one big led stri, but no synchronization guaranteed). From my point of view, the solutions offered by HyperSPI and HyperSerialPico are better in our specific use in an ambient lighting application for a TV or monitor, where synchronization, reliability of connection with a continuous data stream is crucial especially for large LED setups.

**Comment by razqqm** [comment]
UDP-DDP (Distributed Display Protocol) device to overcome the 490 LEDs limitation of UDP-RAW

**Comment by awawa-dev** [comment]
What works best in one UDP packet should stay in one UDP packet. Otherwise, when solving the one problem, we may encounter many others, such as for example `https://github.com/Aircoookie/WLED/issues/2921` This argument did not change my mind, because especially for very large configurations, there are better, more reliable solutions that ensure low latency, which will help us in the first place in this particular ambient lighting niche implemented by HyperHDR. In addition, they can even be benchmarked.

**Comment by awawa-dev** [comment]
The maximum limit of 490 LEDs is solved by implementing the WLED Audio-Reactive-Led-Strip protocol:
https://github.com/awawa-dev/HyperHDR/pull/691
