### ISSUE TITLE
Add software grabber tone mapping to global HDR toggle

### ISSUE THREAD

**Issue by Titanos** [awawa-dev/HyperHDR#631]
#### What problem does this feature solve?

It makes it possible to toggle the software grabber HDR tone mapping via Global HDR toggle and JSON API

#### What does the proposed API look like?

N/A

#### How should this be implemented in your opinion?

N/A

#### Are you willing to work on this yourself?

It is most likely beyond my capabilites

**Comment by mariokakoulli** [comment]
Can confirm from the logs, even with USB capture disabled, when using the API call for HDR from "HyperHDR's components" and "HDR mode", MFGrabber.cpp is being loaded and updated instead of DXGrabber.cpp

Not a C++ dev but looking through the repo it seems there is a wrapper for the Grabbers that should be handling this, i can't really work out where it is being called from initially but could  it be the instance be getting misconfigured as USB, then when the API is being called and the Wrapper tries to handle it it think the USB is active not DX? will look further but not my area of expertise

**Comment by mariokakoulli** [comment]
#637

**Comment by mariokakoulli** [comment]
found a fix, have created above PR for it

**Comment by awawa-dev** [comment]
Also #691 If the switch is no longer needed and there are no reported problems with automatic HDR detection, I will close this.
