### ISSUE TITLE
Failed to open any client sockets? - Can this be ignored?

### ISSUE THREAD

**Issue by stickmanbrad** [awawa-dev/HyperHDR#643]
#### Steps to reproduce

Signing into HyperHDR

#### What is expected?

No unknown pop up errors

#### What is actually happening?

Getting the following error:

2023-09-21T14:28:06.241Z [SERVICE_mDNS] Failed to open any client sockets

Some errors found in the log
The last one:
2023-09-21 14:36:47 [SERVICE_mDNS] Failed to open any client sockets
Some errors are transient (e.g. with the auto-reconnect LED enabled) and can be ignored, others may indicate serious system configuration or operation errors.

#### System

HyperHDR Server: 
- Build:           colored_console_output (Awawa-30351e3/3508d8c-1694899296)
- Build time:      Sep 17 2023 20:46:50
- Git Remote:      https://github.com/awawa-dev/HyperHDR
- Version:         20.0.0.0beta0
- UI Lang:         auto (BrowserLang: en-GB)
- Avail Capt:      Linux (V4L2)
- Database:        read/write

HyperHDR Server OS: 
- Distribution:   Debian GNU/Linux 11 (bullseye)
- Architecture:   arm64
- CPU Type:       Raspberry Pi 4 Model B Rev 1.5
- CPU Revision:   d03115
- CPU Hardware:   BCM2835
- Kernel:         linux (6.1.21-v8+ (WS: 64))
- Qt Version:     5.15.2

**Comment by awawa-dev** [comment]
No mandatory full logs so can't help. The network interface doesn't work for you, so can't help with that either. Still not working mdns is not a critical issues.  If you can live without it, you can ignore it. Otherwise refer to full logs: both HyperHDR and system. Maybe user that runs HyperHDR in your configuration doesnt have rights to open the network socket? Still it is not a HyperHDR issue.
