### ISSUE TITLE
After Update to Debian Bookworm Webserver not showing any data

### ISSUE THREAD

**Issue by Duese123** [awawa-dev/HyperHDR#651]
#### Steps to reproduce
Update Debian from bullseye to bookworm

#### What is expected?
Webserver showing data

#### What is actually happening?
Webserver showing nothing
![image](https://github.com/awawa-dev/HyperHDR/assets/95966691/c3210d8f-fa9b-4dc8-88ab-710872d35c20)
i cannot get logs out of webinterface
Update: seems when grabber is running after some time data is coming
But the system is working normal. Lights are working as usual. Reeinstalling makes no difference

**Comment by awawa-dev** [comment]
Please update the report with full HyperHDR (taken after 2-3 minutes after boot) logs as indicated in the issue template, otherwise it will be closed quickly without any analysis. Also in this particular case data from the HyperHDR->About page form (if the page is available, otherwise update the report with your architecture and QT version) and checking the browser debug console logs (Firefox: Ctrl + Shift + j) for any HyperHDR javascipt errors will be required. Which installer did you use and which version v19/v20?

**Comment by Duese123** [comment]
maybe i was a bit too fast and it was a temporary chrome issue.... I will analyze this. Setup was working more than a year. V20? Do i miss something? Where is a newer version like V19?

**Comment by awawa-dev** [comment]
You can test the latest v20 beta (among other things: the interface has been significantly rewritten and updated using new technologies) and the installers in the latest Github action of the master branch. Currently located here: https://github.com/awawa-dev/HyperHDR/actions/runs/6316763671 artifacts archives at the bottom of the page. If the problem persists, try beta 20 and reopen the case if that doesn't help.
