### ISSUE TITLE
White only Brightness Slider

### ISSUE THREAD

**Issue by NatyaSadella** [awawa-dev/HyperHDR#664]
## Feature request
An option to turn the brightness down on white color only

#### What problem does this feature solve?
Dark colors are outshined by bright white LEDs next to them
#### What does the proposed API look like?
I don't know
#### How should this be implemented in your opinion?
White Brightness Percentage Input Field next to the Brightness Input Field in Image Processing
#### Are you willing to work on this yourself?
Sadly, I can't since I don't know how to code

**Comment by awawa-dev** [comment]
Hi
This is a feature of the equipment you used in your setup, in particular: too many LEDs per meter of tape and/or the LED strip is too far away from the wall and no software will change it, because each LED would have to check its neighbors to see if they are sometimes turned off/dimmed and on its own get darker. I don't even mention the inconsistencies in the brightness of the entire screen that would be caused by something like this... not referring to the problem at all, but regarding the issue of adjusting the brightness of the white color, you have such an option available in the calibration of RGBW strips in HyperSerialEsp8266/ESP32, HyperSPI, HyperSerialPico,

**Comment by awawa-dev** [comment]
You can try to reduce LED density using grouping in the HyperHDR LED geometry setup.
