### ISSUE TITLE
Support for custom python effects

### ISSUE THREAD

**Issue by update-freak** [awawa-dev/HyperHDR#673]
## Feature request

To use LedFX v2 there is a flle for custom python effecs ""UDP RGB Stream Listener"" https://hyperion-project.org/forum/index.php?thread/12082-hyperion-as-udp-listener/&postID=41247#post41247

General idea is to use the microphone from Laptop with LedFX installed that the Leds from HyperHDR (connected in RPi with LibreELEC) will react to the music. 
Here it's mentioned that this will not work with HyperHDR due to a lack of custom python effects (for Hyperion.ng it will work).
Therefore please add the posibility to also use that files (or add an seperate soluation for LedFX v2).

#### What problem does this feature solve?
Sound reactive LED behaviour to music

#### How should this be implemented in your opinion?
Maybe the files from above could be used.

**Comment by awawa-dev** [comment]
Hi
But in HyperHDR you don't need to do it that way using effects... BTW additionally using effects and the Python environment as an intermediary will only generate additional unnecessary resource use and possibly delay.
Since HyperHDR v18 (https://github.com/awawa-dev/HyperHDR/commit/5fb1be1c4bdbc84becfd964a08cb106482b6c4e5) there is already built-in native UDP listener so you can test it for you purpose and let me know about the results.
![obraz](https://github.com/awawa-dev/HyperHDR/assets/69086569/4e5402c5-93d0-45f0-b93a-23f5a31f2baf)

**Comment by update-freak** [comment]
ok, I don't know that. Thanks you very much for your efforts and the explanation. I will try it when I got the hardware (currently I didn't have a system to test).

**Comment by update-freak** [comment]
I checked it and can confirm that its working. Thanks a lot :)
