### ISSUE TITLE
arch64 release

### ISSUE THREAD

**Issue by domeOo** [awawa-dev/HyperHDR#68]
#### What problem does this feature solve?
If u use an RPI4 with arch64 u can't use HyperHDR. I compiled it on my PI like in your Guide, and it works. Would be nice to have it as Official Release from you

**Comment by awawa-dev** [comment]
Hi
Yes, I know the issue. The main problem is current github action scripts and github 500MB limitation on storage for free accounts. Last release took around ~460MB and ordinary push action took ~200MB. And there are some other my repos that take space also. I don't know what happen  after adding arch64 and reaching reach 500MB. At some point migration to paid plan could improve the situation.
BTW I doubt there will be much benefit of using HyperHDR on arch64 system. It's quite a different story than for example Windows 32 vs 64. int64_t data type that is fundamental in the fast video processing is available natively also on 32-bit arm v6/7 OS. Maybe memory bandwidth/access is improved... Must test it some day ;)

**Comment by domeOo** [comment]
I need the arch64 for other things, just want to let hyperhdr run on the same pi. Maybe u can provide me with the info how to bundle in a dpk when I build for arch64. So I can install it like one of your releases? 

Thanks for your great work and best regards

**Comment by awawa-dev** [comment]
I understand. If you managed to compiled the application from sources then you can build installation packages executing ````cpack```` at the end or modify build with ````make -j $(nproc) package```` (than will compile & build packages at once). Scripts for cpack should be prepared by the cmake during configuration automatically if the rpi target is detected.

**Comment by domeOo** [comment]
Thanks it worked perfectly. Maybe the community could take over the cost for Github. I would like to contribute a part to it.

**Comment by bjw-s** [comment]
Hi! I was looking at the Github pricing page (https://github.com/pricing), and as far as I can tell, the 500MB limit does not apply to public projects:

> 500MB of Packages storage
> Free for public repositories

**Comment by awawa-dev** [comment]
Hi
That's not our only repo. Of course, all the developing in the end lands on HyperHDR site when it's finished and ready for release or beta testing. Due to amount of changes and new features it's not ready for that phase now. So the problem exists for the limit and free account (not only the storage but also git action service limit: each version consumes its time for compiling). And now we just hit the operational limit and we won't increase it further: that's for sure, at least for our current model. 

What can we provide it's a change for test in the next release: based on download statistics x64 RPM installers will be removed and aarch64 will be provided. So space limit will be obey but it increases a problem with our github action spending anyway already... so we will see how it will work for us and for users.

**Comment by awawa-dev** [comment]
Implemented in version 17 (beta for testing).
If you have some time, please test it. Reopen the issue if needed.
https://github.com/awawa-dev/HyperHDR/releases/tag/v17.0.0.0beta
