### ISSUE TITLE
Add software current limiting feature

### ISSUE THREAD

**Issue by S-trace** [awawa-dev/HyperHDR#695]
## Feature request

Add a software current limiter (to be able to use low-power supplies). 

#### What problem does this feature solve?

It will allow users to safely use power supplies which can't provide enough power to lit all the LEDs to 100% white.
HyperSerialWLED firmware has it (this feature is the WLED feature).

I have such a power supply, and it worked fine in HyperSerialWLED, but I have upgraded to HyperSerialPico, and now I'm missing this feature. 

I don't want too powerful supply (like a recommended `Total LEDs: 490 (Max. power consumption: 32.3 A)`), as it will burn my eyes away. 
For now, I'm pretty happy with a humble 5V 5A supply (I think 25W is pretty enough for HyperHDR purposes).

The current limiting feature could be implemented in the HyperHDR core without touching LED drivers at all.

#### What does the proposed API look like?

I think it should be something like "software_current_limit_ma" setting in "Image Processing" settings group.

Maybe it should also have the "Advanced" options to calibrate the consumption for particular user's setup using the external ammeter connected in series with power supply and LED strip.

#### How should this be implemented in your opinion?

The HyperHDR should calculate expected current consumption (and limit it if necessary) via soft-capping brightness if the predicted consumption overshoots power supply capacity. 

At low level I see this can be implemented by something like the following:

0. Use the specified LED chip model to set default consumption profile (which may be pre-calibrated for specified voltage (if so - user should enter voltage of the power supply) or just use current specified in the LED chip datasheet at 100% with each of the colors)
1. Calculate sum of the brightnesses for each of the colors around the LED strip just by adding the certain color levels for all the LEDs together (like adding all the blue values for each LED gives totalBlueBrightness, adding all the red values gives totalRedBrightness, and so on for green and white (if any).
2. Divide each total*Brightness by 255 (as 255 is the max possible brightness). to get equivalent*LedsCount values for each color
3. Multiply each of the equivalent*LedsCount with the consumption of a single LED running at 100% brightness of the color to get total*Current for each of the colors, then add all those numbers together to get total LED consumption for the frame.
4. a. If the calculated current consumption is less than power supply capacity - drive the strip(s) directly with original brightness values. So, dark scenes with several bright spots will be rendered without brightness limiting (as the consumption can not overload the power supply) 
4. b. If the calculated current exceeds power supply capacity - calculate downscale factor (`float downscaleFactor = maxSupplyCurrent / predictedCurrent;`) and then multiply each channel's brightness of each LED in the strip to the scaling factor (so the current limiting feature will reduce the overall scene brightness on bright scenes, which will protect the power supply from overloading).

#### Are you willing to work on this yourself?

Yes.
If someone can help me with onboarding with the project building for WebOS - this will be really great,

**Comment by awawa-dev** [comment]
Hi
I understand your problem but I have already said here many times here that I definitely do not plan to introduce such functionality, which in fact is only a workaround (and a bad one at that) for a setup built of improperly selected elements that may be dangerous. Moreover, it is impossible to properly calculate the required power, e.g. in the case of RGBW, it all depends on how the white channel is controlled by the algorithm, because the difference can be quite significant even though we control the same LED strip: everything depends on the algorithm on how we control these 4 channels. Calculations made for HyperSerialPico, which uses the white channel sparingly in its default settings, may be inappropriate for WLED and its calculation method. And if there is an bug in the software (e.g. as in one of the recently WLED versions where the limiter stopped functioning properly), because developers are not infallible and this protection stops working, things will suddenly become unpleasant. So I'm sorry but `It will allow users to **safely** use power supplies which can't provide enough power` is not completely safe at all.
