### ISSUE TITLE
Bring back Raspi SD card image build

### ISSUE THREAD

**Issue by rorosaurus** [awawa-dev/HyperHDR#699]
#### What problem does this feature solve?

Deprecating RaspberryPi OS (SD card image installation) might not be necessary anymore? It seems you can download the image separate from Imager now.
https://www.raspberrypi.com/software/operating-systems/

There's a couple other solutions here for wifi config: https://raspberrypi.stackexchange.com/questions/144850/headless-wi-fi-setup-without-the-rpi-imager-bootfs-wpa-supplicant-conf-not-supp

Though that might not be worth the effort to chase. Perhaps we could just require ethernet at first to SSH and run NetworkManager?

#### What does the proposed API look like?
n/a

#### How should this be implemented in your opinion?
I would say try to replicate the old build configs as much as possible, to not waste time.

#### Are you willing to work on this yourself?
I'd be happy to help with documentation! I'd be more comfortable committing after I've familiarized myself with this project a little more.

**Comment by awawa-dev** [comment]
Hi
Given this attitude towards the problems reported by users (`https://github.com/raspberrypi/bookworm-feedback/issues/72`), I personally do not intend to do anything... but rather focus on alternatives to RPi which I have already written about (Intel N100/N200). Maybe it's just the straw that broke the camel's back for RPi after previous problems with availability and now with significant problems with OS images themselves. Remaining on the Bullsyeye images could be a solution (after patching the critical udev bug in the last image), but RPi 5 is not supported by this system and they have no intention for such release, so the circle closes. And since RPi is closed-hardware workaround for Bullseye & RPi5 is also not possible. In that thread I linked you have a hack on how to get around it, but such solutions are short-lived at best. While the switch to nmcli is somewhat forced by Bookworm, the proposed solution (which must have cost them a lot of work, so it was intentional) limits the functionality only to their flasher.

Maybe when the long-promised cloud-init finally appears, I will come back to this issue, but currently it is only talked about.

**Comment by awawa-dev** [comment]
OK, I tested it and the workaround seems to work.
The next HyperHDR v20beta2 release will use these Raspberry Pi OS images as the basis for SD images:

https://downloads.raspberrypi.org/raspios_lite_arm64/images/raspios_lite_arm64-2023-05-03/2023-05-03-raspios-bullseye-arm64-lite.img.xz
https://downloads.raspberrypi.org/raspios_lite_armhf/images/raspios_lite_armhf-2023-05-03/2023-05-03-raspios-bullseye-armhf-lite.img.xz

They are based on Debian Bullseye, the old Wi-Fi configuration still works (wpa_supplicant), you can use any image flasher and when building "apt update udev" is performed, so the critical error for serial port devices is gone. Raspberry Pi 5 will not work with them, use the official Raspberry Pi Imager tool to install the Bookworm based version if you don't mind their practices.

**Comment by awawa-dev** [comment]
SD images were included in the latest v20beta2 release
