### ISSUE TITLE
Android Grabber!?

### ISSUE THREAD

**Issue by diegoweb** [awawa-dev/HyperHDR#714]
#### What problem does this feature solve?
This would allow Android Devices (like Fire TV sticks, Android TV Boxes, etc) to directly send image data to the HyperHDR server, without the need of external hardware (hdmi splitter, etc).

#### What does the proposed API look like?
https://github.com/abrenoch/hyperion-android-grabber

#### How should this be implemented in your opinion?
The same as in the Hyperion app, provide an APK for Mobile and TV usage.
Since HyperHDR is a fork from Hyperion, probably it's just a matter of adapting the source code from the Hyperion Android Grabber to support HyperHDR server.

#### Are you willing to work on this yourself?
I don't have the skills.

**Comment by awawa-dev** [comment]
Hi
As far as I know, Hyperion Android Grabber is a closed source application (only certain parts of the code are available). But it should also work with HyperHDR using Protobuffer, so why implement it again? Especially since Google makes it almost impossible to capture any software capturing these days due to DRM? Such solutions probably have no future, unless you use an application that does not require DRM, because even having root (which theoretically allows for more) is detected by Widevine.

**Comment by diegoweb** [comment]
> Hi As far as I know, Hyperion Android Grabber is a closed source application (only certain parts of the code are available). But it should also work with HyperHDR using Protobuffer, so why implement it again? Especially since Google makes it almost impossible to screen capture these days due to DRM? Such solutions probably have no future, unless you use an application that does not require DRM, because even having root (which theoretically allows for more) is detected by Widevine.
Well... regarging HyperHDR work with protobuffer, before oppening the issue here in Github, I tried to run the app and make it connect to my HyperHDR server, but that did not work.

And I will be mainly using with apps that doesn't require DRM, so that's why I want a simplified setup.
I haven't bought the LEDs and ESP32 board yet, I'm just trying to make sure I will first be able to connect HyperHDR with the Android Grabber, so I can save some bucks and also keep the back of my TV cleaner (since it isn't flat with the wall).

**Comment by awawa-dev** [comment]
I understand but I don't plan similar app as I explained the reasons. Similarly I can't provide support for such legacy solution because I don't have such setup: all is up to the Community. Also android grabber seems to be abandon project because last important commit was submitted many years ago, and due to partial closed sources you won't get support for the app anywhere. 
There was an alternative cheap solution like piccap for LG tv, but it was patched some time ago.. maybe in future it will be available again. It's not our fault you can't have a cheap and simple setup to work with your purchased video content... the industry is probably a more appropriate audience for your complaints.

**Comment by AstaRom** [comment]
> I tried to run the app and make it connect to my HyperHDR server, but that did not work.

You need to change the priority in the application settings.
- https://github.com/abrenoch/hyperion-android-grabber/issues/179

**Comment by diegoweb** [comment]
> I understand but I don't plan similar app as I explained the reasons. Similarly I can't provide support for such legacy solution because I don't have such setup: all is up to the Community. Also android grabber seems to be abandon project because last important commit was submitted many years ago, and due to partial closed sources you won't get support for the app anywhere.
> There was an alternative cheap solution like piccap for LG tv, but it was patched some time ago.. maybe in future it will be available again. It's not our fault you can't have a cheap and simple setup to work with your purchased video content... the industry is probably a more appropriate audience for your complaints.

OK! Thank you.



> You need to change the priority in the application settings.

I did set between 100 and 200, it didn't work.
I suppose even without a WLED interface, this app should be able to connect to a HyperHDR/Hyperion server without anything set up, right?

Since this is the connection between the HyperHDR/Hyperion server to collect image data, and has nothing to do with the LED strip.

Well.... anyway, I will see what I can do.
Maybe set in standby the idea of having this led stuff in my TV for now, it would get too expensive and bulky in my TV :(

**Comment by awawa-dev** [comment]
>I suppose even without a WLED interface, this app should be able to connect to a HyperHDR/Hyperion server without anything set up, right?
Since this is the connection between the HyperHDR/Hyperion server to collect image data, and has nothing to do with the LED strip.

Did you check video live preview? Also verify if correct port is enabled both in HyperHDR and in the Android grabbers. Something should be in the HyperHDR logs if there is an attempt of connection.

**Comment by awawa-dev** [comment]
BTW protobuffer server is disabled in HyperHDR by default. But I assumed that you enabled it.

**Comment by diegoweb** [comment]
> BTW protobuffer server is disabled in HyperHDR by default. But I assumed that you enabled it.

OK, that did it.
I thought this would be enabled by default.

Thank you!
