### ISSUE TITLE
When disabling HDR ouput freezes on device

### ISSUE THREAD

**Issue by tungmeister** [awawa-dev/HyperHDR#721]
## Bug report, debug log and your config file (FULL LOGS ARE MANDATORY)

[logs](https://pastebin.com/D9cXkceq)
#### Steps to reproduce
Disable HDR (Global)
#### What is expected?
LEDs should continue to update
#### What is actually happening?
When HDR (Global) is disabled the LEDs stop updating on my second WLED device (below cabinet) after about 1 second. though my main device (around screen) keeps updating as expected. As soon as HDR (Global) is reenabled the second device resumes updating the LEDs as expected. (ignore the "disconnected" errors in the log - that was me attempting to diagnose) 
#### System

HyperHDR Server: 
- Build:           (HEAD detached at v20.0.0.0beta1) (GitHub-ccd22a1/558c7e0-1703192848)
- Build time:      Dec 23 2023 14:59:36
- Git Remote:      https://github.com/awawa-dev/HyperHDR
- Version:         20.0.0.0beta1
- UI Lang:         auto (BrowserLang: en-GB)
- Avail Capt:      Linux (V4L2)
- Database:        read/write

HyperHDR Server OS: 
- Distribution:   Debian GNU/Linux 12 (bookworm)
- Architecture:   arm64
- CPU Type:       Raspberry Pi 5 Model B Rev 1.0
- CPU Hardware:   c04170
- Kernel:         linux (6.1.0-rpi6-rpi-2712 (WS: 64))
- Qt Version:     5.15.8

**Comment by awawa-dev** [comment]
Verify your live preview (must switch to instance1 first), I suspect probable black screen. Then remove your custom LUT and see if that helps. Next step is disabling the blackboarder detector.

**Comment by tungmeister** [comment]
Sorry, it was the black bar detection - when in HDR it wasn't sufficiently sensitive. I've increased the tolerance and now it's ok. I think Black isn't truly black when in SD mode requiring the tolerance to be increased.
![image](https://github.com/awawa-dev/HyperHDR/assets/127809/a846567e-5429-4560-aeef-b2c44afe0585)
vs HDR enabled (non HDR content)
![image](https://github.com/awawa-dev/HyperHDR/assets/127809/03b555fa-dac7-41c3-8180-c8970e1708b9)

**Comment by awawa-dev** [comment]
Which grabber? ms2130? If so make sure you read the update: https://github.com/awawa-dev/HyperHDR/discussions/499#discussioncomment-7978410

**Comment by tungmeister** [comment]
Yeah, ms2130.  Looking at the capabilities of mine, it must have the newer firmware.  Can the "original" version be flashed?

**Comment by awawa-dev** [comment]
Which model you have:  A, B or something other? In mentioned thread you will find links: one to the article and one to the application (just be careful, although it was scanned and nothing suspicious was detected). Also backup of earlier version of firmware could be found there.

**Comment by tungmeister** [comment]
it's one of the random named ones in the metal cases - same hardware IDs as the others though. I'll have a good look through the thread tomorrow, it's quite extensive!

**Comment by awawa-dev** [comment]
How did you test SDR (app? if HyperHDR tone mapping was disabled? **which version of LUT table?**) and do you have a screenshot?
Try to capture this image https://github.com/awawa-dev/HyperHDR/blob/v19.0.0.0/resources/lut/calibration_sdr.png

**Comment by awawa-dev** [comment]
Maybe you didn't disconnect the grabber after flashing and it didnt reboot? Anyway differences are clearly visibly for SDR. Here's my fresh results from HyperHDR app:
New firmware:
![new_firmware](https://github.com/awawa-dev/HyperHDR/assets/69086569/775b5880-6013-404a-9948-63e70d9443be)
Old firmware:
![old_firmware](https://github.com/awawa-dev/HyperHDR/assets/69086569/afb81dc1-1521-46d1-a03e-0ed98782d115)
On input (26,26,26): new firmware capture it as (38,38,38), old firmware (26,26,26)
On input (26,26,0): new firmware capture it as (36,40,17), old firmware (24,27,0)
On input (0,26,26): new firmware capture it as (18,41,35), old firmware (0,26,23)
....
The rest you can check yourself.
Anyway the initial issue was explained & resolved so that's all I think. You can follow our latest findings in the MS2130 thread.
