### ISSUE TITLE
Usb grabber does not work most of the times.

### ISSUE THREAD

**Issue by GhostgamesDHG** [awawa-dev/HyperHDR#742]
Y

Hyperhdr doesnt see the USB grabber and I can see it in the ssh screen. So whats going on?

LOG
--> https://pastebin.com/qTdD1t5r

#### What is expected?
For the system to find the usb graber normally

#### What is actually happening?
Most of the times it cant find my usb grabber. And in the ssh log I can find the grabber, but in the hyperhdr web interface not.

#### System

HyperHDR status:
On
Platform:
Linux (V4L2)
Video device
Video mode
Controller type:
wled
Instance:
hometv
Your HyperHDR version:
20.0.0.0beta1
Latest HyperHDR version:
v20.0.0.0beta1

**Comment by GhostgamesDHG** [comment]
apparently if I restart hyperhdr it shows.
LOG https://pastebin.com/qbm4dT4V

How can I get this automaticly, because this system will not be for me so I cannot leave it like this.

**Comment by awawa-dev** [comment]
Hi
1 normally such a message means that the user does not have permissions, but if it works later, it is probably not the case
2 Your SD card/disk is dying which is causing a very slow loading of a key OS module (v4l)
3 You are using a grabber that is causing problems in this module

You can find more in dmesg. This is not a HyperHDR problem and diagnosing it in each specific case is a nightmare (a similar issue comes back once a year, last time it was probably caused by some fake UTV 007): I am not taking up this topic.

**Comment by awawa-dev** [comment]
Not planned. The main key is to start HyperHDR as soon as possible, without any delay. Similar to shut it down. If some other software takes longer to start-up (and it's actually an unwanted side-effect and not intentional) then maybe it might actually work in your case. You can always delay service start-up by modifying the HyperHDR service file and adding any delay you want.

**Comment by awawa-dev** [comment]
Service file:
`/etc/systemd/system/hyperhdr@.service`
add to service section:
`ExecStartPre=/bin/sleep 30`
Apply changes:
`sudo systemctl daemon-reload`

**Comment by GhostgamesDHG** [comment]
> Service file: `/etc/systemd/system/hyperhdr@.service` add to service section: `ExecStartPre=/bin/sleep 30` Apply changes: `sudo systemctl daemon-reload`

Thank you, I will try this :)
