### ISSUE TITLE
Update to v20 crashed during start

### ISSUE THREAD

**Issue by Duese123** [awawa-dev/HyperHDR#781]
#### hyperhdr will not start
Calibration config '0' for LED segment: [1, 62]
00:56:27.895 LED_CALIBRATION0       : <DEBUG> LedCalibration.cpp:101:setAdjustmentForLed() | Calibration config '0' for LED segment: [300, 338]

HyperHDR caught signal :SIGBUS
00:56:27.905 CORE                   : <ERROR>   /lib/arm-linux-gnueabihf/libc.so.6(__default_rt_sa_restorer+0) [0x7579d280]
00:56:27.905 CORE                   : <ERROR>   hyperhdr() [0x870b4]
00:56:27.906 CORE                   : <ERROR>   hyperhdr() [0x87da8]
00:56:27.906 CORE                   : <ERROR>   hyperhdr() [0x6e4b4]
00:56:27.906 CORE                   : <ERROR>   /usr/share/hyperhdr/bin/../lib/libQt5Core.so.5(+0x2e4a70) [0x75eeea70]
00:56:27.906 CORE                   : <ERROR>   /usr/share/hyperhdr/bin/../lib/libQt5Core.so.5(QThread::started(QThread::QPrivateSignal)+0x5c) [0x75caa8e4]
00:56:27.906 CORE                   : <ERROR>   /usr/share/hyperhdr/bin/../lib/libQt5Core.so.5(+0xa31f8) [0x75cad1f8]
Bus error

With delete database hyperhdr is starting. But import old v19 settings will lead again into this. Downgrade to v19 working again.
#### System

Settings:
[HyperHDR-19.0.0.0-Backup-2024-02-25.json](https://github.com/awawa-dev/HyperHDR/files/14394844/HyperHDR-19.0.0.0-Backup-2024-02-25.json)

**Comment by awawa-dev** [comment]
Hi
Sorry for the inconvenience. One thing is how we should deal with incorrect user configuration and I will fix it. But the core of the problem is that you are using the wrong starting index: it should start from 0, not 1. So not 1-62 300-338, but 0-61 299-337. Otherwise, LED at level 338 will cause a failure and LED 0 is not suitable for any configuration. I will provide a patch that will protect HyperHDR from this later, but your configuration is wrong anyway.

**Comment by Duese123** [comment]
Ah okay thanks!! Good to know! I will try to change! Thanks for fast reply
