### ISSUE TITLE
HyperHDR stops responding, can't even terminate process

### ISSUE THREAD

**Issue by brs677** [awawa-dev/HyperHDR#851]
After a couple minutes, the webUI no longer works (404, page not found or, HyperHDR not running or Bad WLAN Connection.) The system tray icon sometimes allows for right clicking, but menu options don't work; Quit does nothing except sometimes remove the tray icon, but HyperHDR continues to run and eats up more and more memory. Trying to end the task does nothing, and trying to end the processes gets "Unable to terminate process, The operation could not be completed. Access is denied." The only solution is to restart my PC. 

Happened with HyperHDR v20.0.0.0, which I uninstalled, deleted its directory from "programs" and the ".hyperhdr" one from appdata. Reinstalled but the problem persisted. Uninstalled that as well, and installed HyperHDR v19.0.0.0 but that also had the same problem.

I'm attempting to get the logs but I can't access them through the webui.

**Comment by awawa-dev** [comment]
This issue section assumes (unless it is a feature request) that if the user has a problem, he is able to provide the required details, including full logs, which are almost always necessary for error diagnosis. This is the minimum because the diagnostic process is usually tedious and experience shows that if the user is not patient enough to provide the minimum information that may lead to the problem, it is only a waste of time because at some point he will probably give up. So let's try not to make a trash here.

Here you didn't even provide information about what operating system you are using, which is a big obstacle because HyperHDR is used on many hardware and OS platforms. However, you can ask yourself whether if the application on any of them does not start at all, it is rather a problem with the user configuration or the application. I would suspect (again from experience) a lot of new reports, and there have been no such reports in recent years, either with version 20 or 19.

If you want, you can start a thread in the discussions section instead, because there the rules are looser and maybe someone from the community will come up with an idea,
