### ISSUE TITLE
Invalid CRC at: 13

### ISSUE THREAD

**Issue by asm0dey** [awawa-dev/HyperHDR#858]
## Bug report, debug log and your config file (FULL LOGS ARE MANDATORY)

Log: https://pastebin.com/byZZd5fM
Config: https://pastebin.com/chWERmgf

#### Steps to reproduce

1. Turn on HDR on Windows
2. Open the HyperHDR LUT color calibration in MS Edge or Vivaldi

#### What is expected?

Calibration finishes

#### What is actually happening?

3. It blinks several (or one?) times and nothing happens, in logs there is no further progress on relatively powerful hardware

#### System

```
HyperHDR Server: 
- Build:           (HEAD detached at v20.0.0.0) (awawa-dev-9e960c9/52f12b4-1711236142)
- Build time:      Mar 23 2024 23:28:49
- Git Remote:      https://github.com/awawa-dev/HyperHDR
- Version:         20.0.0.0
- UI Lang:         auto (BrowserLang: en-GB)
- Avail Capt:      Windows (Microsoft Media Foundation)
- Database:        read/write

HyperHDR Server OS: 
- Distribution:   Windows 10 Version 22H2
- Architecture:   x86_64
- CPU Model:      Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz
- Kernel:         winnt (10.0.19045 (WS: 64))
- Qt Version:     6.5.3
- Browser:        Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0 
```

**Comment by awawa-dev** [comment]
You have the CRC encoded at the bottom of the frame as white/black boxes. Unfortunately I can't diagnose the problem here based on the description, but so far almost always the captured image in similar cases is the frame is distorted/cropped or the browser status appears at the bottom/top/side, so the calibration mosaic does not take up the full frame in the preview video and the coordination of individual boxes did not correspond to the captured reality.

**Comment by awawa-dev** [comment]
BTW DirectX grabber doesnt need a calibration since v20.

**Comment by asm0dey** [comment]
Since hyperhdr crashes during the calibration on my LG TV, I hoped to
calibrate it on another a machine running Windows and then export the
profile to my LG.

It's interesting that something is cropped/distorted, any ideas how to fix
it? I didn't see any status bar or anything...

**Comment by awawa-dev** [comment]
There was a fixed for grabber-less build configuration merged recently. Using DirectX calibration won't help you at all for webos: it's capturing system & quality is something different than usb grabbers, no one knows how it process the video signal, no LG documentation is available and it depends on the TV model. Calibration could help a bit but the problem is not perfect capturing process. Usually webos has calibration error score around 20000-25000 and good grabbers below 1000. Still I didn't design it for Webos.

**Comment by asm0dey** [comment]
Oh I see, thanks. I've reported the crash to the downstream, so we'll see
