### ISSUE TITLE
Whites on a RGBWW are showing red and flashing 

### ISSUE THREAD

**Issue by Bboy486** [awawa-dev/HyperHDR#89]
I am running hyperHDR with rgbww leds. When I have a pure 

https://user-images.githubusercontent.com/16495657/126928573-91b923d9-6694-4099-96a4-d8fc6e94d3b6.mp4

white background the LEDs flash and show red instead of a warm white (the ww).

Hardware
TCL 4K TV, wiistar HDMI to USB 3.0 Video Capture USB C Video Card with HDMI Loop Out and 4K HDMI Splitter 1x2 4K@60Hz 4:4:4 HDR D-o-l-b-y Vision D-o-l-b-y Atmos Compatible into a Yamaha AVR.
Rpi4 running hyperhdr.

**Comment by awawa-dev** [comment]
Seems like problems with your LED setup (flashing) or configuration (3 bytes RGB instead of 4 bytes RGBW). That's what I'm guessing without a logs, LED driver configuration, screenshot from HyperHDR's video live feed.

**Comment by Bboy486** [comment]
Where is the 4 byte located? 
How can I share the information you are requesting?

**Comment by Bboy486** [comment]
@awawa-dev why did you close this?

**Comment by awawa-dev** [comment]
Because your are missing basic details that could indicate an application issue and it's seems it's rather a software configuration issue or led strip build hardware problem. Please provide details your LED driver configuration, logs, how it's connected and video live feed screenshot to exclude problem with a video signal (dolby vision is not supported by any mainstream grabber on the market) and start a topic  in the discussion. If you have access to esp8266 or esp32 for a few bucks then using WLED it could be a great help for the diagnostic.

**Comment by Bboy486** [comment]
Sorry! I was not sure what to share. 
Here are the logs https://pastebin.com/eYsYA0hE

Here is my config https://drive.google.com/file/d/1ywKt9Q1rOxyMKmNNqwTY0XwlmK2aDb8T/view?usp=drivesdk

Screenshot of live 
![Screenshot_20210727-164631_Chrome](https://user-images.githubusercontent.com/16495657/127241637-8a94964b-57e8-4f92-8fbe-e467e9cb9a36.jpg)

WS281x
![Screenshot_20210727-164835_Chrome](https://user-images.githubusercontent.com/16495657/127241777-dbafcb34-4202-44a1-b68e-cead1aa68e71.jpg)
![Screenshot_20210727-164631_Chrome](https://user-images.githubusercontent.com/16495657/127241778-6f2820c5-5968-4da4-9297-08226598938f.jpg)

**Comment by awawa-dev** [comment]
Thanks! That's much better :)
Just to confirm: RGBWW means RGB Warm White?
If that's true then you probably have sk6812 RGBW led strip and you should not use WS281x driver (although it has an option: 'use RGBW protocol' and you may give it a try and maybe it will work, because now it works in 3 bytes RGB mode) but  sk6812 driver. BTW use of external ESP8266/ESP32 is recommended to drive that types of led.

PS:
Please upgrade HyperHDR to v16 ;)

**Comment by Bboy486** [comment]
Yup that's warm white. Not my favorite but it was what I had. 

SMD 5050 RGB LED Strip Waterproof 5M 300LED DC 12V RGBW RGBWW Fita LED Light Strips Flexible Neon Tape Luz Monochrome

I did try rgb protocol but it gave me funky results. 

When I try sk6812spi the LEDs don't turn on.

**Comment by awawa-dev** [comment]
WS281x in 3 bytes RGB mode is definitely no way to go: beside different protocol the data buffer is smaller than it should be with 4 bytes RGBW (that's why led strip last segment is not controlled by the application).
GPIO18 on the screenshot means that you try to use PWM mode with WS281x driver and you should use different clock pinout with Rpi when SPI sk6812 led driver is used: probably because of that you had no reaction from the led strip when you tried it.

**Comment by awawa-dev** [comment]
And I hope your led strip is not similar to something like that:
![obraz](https://user-images.githubusercontent.com/69086569/127293504-c5b66853-c2f5-4ece-854e-d39a80e5f6b1.png)

**Comment by Bboy486** [comment]
By clock pinout you mean try a different pin line gpio 10? 

Where do I change the 3 to 4 bytes in the settings? Or is that driven by the driver?

**Comment by Bboy486** [comment]
> Yes, GPIO10. sk6812 driver uses 4 bytes RGBW on default (there are very rare sk6812 RGB led strips but that's not the case).
> Make sure that you have a common ground between Rpi and the led strip also.

Thank you. That is working better. However a new issue arose. The signal from the HDMI handshake is getting interrupted and cuts the signal. The screen goes black and then the picture reappears. The lights do stop at that point.

**Comment by awawa-dev** [comment]
The handshake could disrupt the video stream: all grabbers that I have behave in such way when my PC is renegotiating the HDMI protocol when the video resolution is change for a new movie. It can last for 2-3 seconds at most. But then the video stream is back and led strip should be back online. If your led strip remains off then probably the capturing stream encounter critical error during that phase but it's a particular hardware problem as the grabber can't resume the capturing. Again more details should be in logs.

**Comment by Bboy486** [comment]
> The handshake could disrupt the video stream: all grabbers that I have behave in such way when my PC is renegotiating the HDMI protocol when the video resolution is changed for a new movie. It can last for 2-3 seconds at most. But then the video stream is back and the led strip should be back online too. If your led strip remains off then probably the capturing stream encountered critical error during that phase but it's a particular hardware problem as the grabber can't resume the capturing. Again more details should be in logs.

Does yours continue when watching the movie, because mine does. The LEDs do go back on but the disruption happens several times during the playback. Would any of this have to do with HRD to SDR tone mapping? 

Is there a way to see past logs? Mine is only showing today and the issue happened last night.

**Comment by awawa-dev** [comment]
HDR to SDR tone mapping has nothing to it. It's about driver/hardware that provides the video stream: tone mapping is done later. My mpc-hc with madVR filter change the output resolution almost before every movie to choose best. Dont have any problems with Ezcap 269,320,321 and macrosilicone ms2109. it's only 1-2 seconds at the beginning. Internal logs are lost after each restart of HyperHDR. It's possible to run HyperHDR in the console and redirect log output to a file but it's a last resort solution, a bit more complicated.

**Comment by awawa-dev** [comment]
> The LEDs do go back on but the disruption happens several times during the playback. 

If I had to guess it's related to poor HDMI cables quality.

**Comment by Bboy486** [comment]
It just happened so here is the log
https://pastebin.com/n0WPZZi1

I see bad entries but not sure what it means. I have new cables on order and will look into ESP32

**Comment by awawa-dev** [comment]
Logs look clear, but please upgrade to v16 because I can't support v14 which is quite different from the current one.
The MJPEG bad frames are typical for some USB grabbers under Linux. Not sure if it's a manufacture design flaw, kernel driver or USB bus problem. But their number is not significant.
The video stream and led driver worked without any disruption for about 12 minutes to the log's end. HDMI cables are main suspect. Especially if the signal is disrupted also on the TV. Less probably reason is damaged USB grabber. I don't think that there is a power supply problem with the grabber because such thing leaves a trace in the logs.

**Comment by Bboy486** [comment]
I have some new cables in order. What would I be seeing in the logs if the pi can't handle the LEDs?

I will have to research esp32 as I'm not familiar with it.

**Comment by awawa-dev** [comment]
Usually it leaves no trace...it's just not working or you may experience some random flashing from time to time. But it doesn't disrupt the video signal or doesn't cause any HDMI handshaking.
Better solution than ESP32 is ESP8266 (for example wemos d1 mini clone with *CH340G* or *CP2104* serial chip on board, avoid CP2102!).
- it's cheaper and we do not need a dual core at all (in fact dual core can cause some problems with WLED sometimes)
- you can connected it by the cable or WIFI and use WLED, HyperSerialESP8266 or HyperSerialWLED

Regardless if you using Rpi or ESP to drive a LED strip it's recommended to use a level shifter (not required in most case but it should be used). It's explained here: [https://hyperhdr.blogspot.com/2020/12/my-build-log-using-sk6812-rgbw-led.html#chapter3](url) or you can use 74AHCT125 chip

**Comment by Bboy486** [comment]
> Regardless if you using Rpi or ESP to drive a LED strip it's recommended to use a level shifter (not required in most case but it should be used). It's explained here: https://hyperhdr.blogspot.com/2020/12/my-build-log-using-sk6812-rgbw-led.html#chapter3 or you can use 74AHCT125 chip

I saw that when I was setting it up but I measured the voltage and didnt have an issue with the number of lights I am driving. I can look into it again but I do not believe it to be a voltage issue.
