### ISSUE TITLE
Drop frame rate/resolution of grabbers when source signal dies

### ISSUE THREAD

**Issue by vena** [awawa-dev/HyperHDR#93]
With signal detection enabled, the instance is disabled and LEDs are turned off but the grabber continues to capture frames. An option to drop the frame rate and resolution in a no-signal state could save significant CPU at idle.

Pi 3 B+, HyperHDR 16.0.0.1 with a MicroSilicon MS2109 USB grabber using YUYV at 1280x720 with quarter frame mode and spare processing enabled. Testing frame rate cpu usage from uvcvideo while signal is OFF: 30 fps: 20%, 5 fps: 12%

If I also drop the resolution to the lowest supported, 640x480, CPU usage from uvcvideo drops to <5%.

Signal return is still detected immediately at 640x480/5fps

#### What problem does this feature solve?

Idle CPU usage

#### What does the proposed API look like?

n/a

#### How should this be implemented in your opinion?

When signal detection is checked, reveal an input to set a different frame rate and resolution from supported values when no signal is detected. Switch grabber to those settings before "disabling" instance.

#### Are you willing to work on this yourself?

Unfortunately I do not know C++. I attempted to solve this with a python daemon watching priorities from the API, but i couldn't find a reasonable/obvious way to manage grabber frame rate from there...

**Comment by awawa-dev** [comment]
OK, next version (v17)

**Comment by awawa-dev** [comment]
Since there is new automatic signal detection that based on the calibration data we can't change the video resolution. The only real option is the framerate. Most of grabber has only one framerate mode for selected resolution so we must lower frame-processing in software.
 
Implemented in version 17 (beta for testing). Details in the change log. It causes quite a large drop of CPU usage depending on the video format and current frame-rate (the lower the framerate is the lower is the benefit while 'nosignal', grabber via kernel still takes its resource: bigger for uncompressed YUV smaller for MJPEG).
If you have some time, please test it. Reopen the issue if needed.
https://github.com/awawa-dev/HyperHDR/releases/tag/v17.0.0.0beta
